### ISSUE TITLE
Crash when playing a song

### ISSUE THREAD

**Issue by LovelyA72** [PolyMeilex/Neothesia#26] opened 2022-09-23 02:55 UTC
```
C:\Users\Honoka\Downloads>neothesia.exe
[2022-09-23T02:54:52Z INFO  neothesia::scene::menu_scene::iced_menu] File path = "C:\\Users\\Honoka\\Downloads\\KiRa-KiRa Sensation!.mid"
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src\scene\menu_scene\iced_menu.rs:202:75
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
Version 0.0.13

**Comment by whc2001** [comment] 2022-09-23 04:30
```
PS C:\Users\WHC\Desktop> $env:RUST_BACKTRACE="full"
PS C:\Users\WHC\Desktop> .\neothesia.exe
[2022-09-23T04:30:31Z INFO  neothesia::scene::menu_scene::iced_menu] File path = "D:\\Keyboard\\MUSICDAT\\LSY.MID"
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src\scene\menu_scene\iced_menu.rs:202:75
stack backtrace:
   0:     0x7ff7d01f1a4f - <unknown>
   1:     0x7ff7d0209b8a - <unknown>
   2:     0x7ff7d01ee8c9 - <unknown>
   3:     0x7ff7d01f423b - <unknown>
   4:     0x7ff7d01f3e2e - <unknown>
   5:     0x7ff7d01f4831 - <unknown>
   6:     0x7ff7d01f46b2 - <unknown>
   7:     0x7ff7d01f2357 - <unknown>
   8:     0x7ff7d01f43c9 - <unknown>
   9:     0x7ff7d0238f15 - <unknown>
  10:     0x7ff7d0238dbc - <unknown>
  11:     0x7ff7cfc31f3c - <unknown>
  12:     0x7ff7cfc361c6 - <unknown>
  13:     0x7ff7cfc9e895 - <unknown>
  14:     0x7ff7cfc3499e - <unknown>
  15:     0x7ff7cfbce158 - <unknown>
  16:     0x7ff7cfc3e5f1 - <unknown>
  17:     0x7ff7cfc2076c - <unknown>
  18:     0x7ff7cfc1fe58 - <unknown>
  19:     0x7ff7cfc3e983 - <unknown>
  20:     0x7ff7cfc1fa3e - <unknown>
  21:     0x7ff7cfc0ebb7 - <unknown>
  22:     0x7ffe5811e858 - CallWindowProcW
  23:     0x7ffe5811e3dc - DispatchMessageW
  24:     0x7ffe58130bc3 - SendMessageTimeoutW
  25:     0x7ffe59010e34 - KiUserCallbackDispatcher
  26:     0x7ffe56ef1704 - NtUserDispatchMessage
  27:     0x7ffe5811e2ea - DispatchMessageW
  28:     0x7ff7cfc00e24 - <unknown>
  29:     0x7ff7cfbff1e8 - <unknown>
  30:     0x7ff7cfbfffb2 - <unknown>
  31:     0x7ff7cfbced96 - <unknown>
  32:     0x7ff7cfbcedac - <unknown>
  33:     0x7ff7d01e752e - <unknown>
  34:     0x7ff7cfc00207 - <unknown>
  35:     0x7ff7d02115bc - <unknown>
  36:     0x7ffe57ce7034 - BaseThreadInitThunk
  37:     0x7ffe58fc26a1 - RtlUserThreadStart
```

**Comment by PolyMeilex** [comment] 2022-09-23 08:43
The code you are pointing to no longer exists on master so I'll just do a release and we'll see if that helps

**Comment by PolyMeilex** [comment] 2022-09-23 10:41
Or actually, could you try the master build first:
[windows-artifact.zip](https://github.com/PolyMeilex/Neothesia/files/9632943/windows-artifact.zip)
If it fixes the problem, I'll do a release.

**Comment by whc2001** [comment] 2022-09-24 03:02
> Or actually, could you try the master build first: [windows-artifact.zip](https://github.com/PolyMeilex/Neothesia/files/9632943/windows-artifact.zip) If it fixes the problem, I'll do a release.

Seems like the problem is gone in this version

**Comment by PNRYates** [comment] 2022-09-25 07:26
not gone on macos

**Comment by PolyMeilex** [comment] 2022-09-26 18:32
0.0.14 released with the fix included

**Comment by whc2001** [comment] 2022-10-04 18:24
For Windows seems like it's working fine with the latest release.

**Comment by PolyMeilex** [comment] 2022-10-04 19:01
> not gone on macos

If it still causes problems, please open a separate issue, preferably with logs.

> For Windows seems like it's working fine with the latest release.

Thank you!

**Closed by PolyMeilex** 2022-10-04 19:01 UTC
